import { useEffect, useState } from 'react'
import type { ReactNode } from 'react'
import { Link, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import { BookOpen, LayoutDashboard, LogOut, Menu, Search, Settings2, Tags, Upload, X } from 'lucide-react'
import { api, dashboard, logout, me, papers, Paper, setupStatus } from './lib/api'

function Shell({ children }: { children: ReactNode }) {
  const nav = useNavigate(); const loc = useLocation(); const [open, setOpen] = useState(false)
  const links = [{ to: '/app/dashboard', label: '概览', icon: LayoutDashboard }, { to: '/app/papers', label: '论文库', icon: BookOpen }, { to: '/app/import', label: '导入论文', icon: Upload }, { to: '/app/taxonomy', label: '标签与分类', icon: Tags }, { to: '/app/settings/security', label: '安全设置', icon: Settings2 }]
  return <div className="app-shell"><aside className={open ? 'sidebar open' : 'sidebar'}><div className="brand"><span className="brand-mark">PA</span><span>Paper Atlas</span><button className="icon-button mobile-close" onClick={() => setOpen(false)} aria-label="关闭导航"><X size={18}/></button></div><nav>{links.map(({to,label,icon: Icon}) => <Link key={to} to={to} onClick={() => setOpen(false)} className={loc.pathname.startsWith(to) ? 'nav-link active' : 'nav-link'}><Icon size={18}/><span>{label}</span></Link>)}</nav><div className="sidebar-foot"><div className="status-dot"><span/> 本地知识库</div><button className="nav-link" onClick={async () => { await logout().catch(() => {}); nav('/auth/login') }}><LogOut size={18}/>退出登录</button></div></aside><div className="main-area"><header className="topbar"><button className="icon-button mobile-menu" onClick={() => setOpen(true)} aria-label="打开导航"><Menu size={20}/></button><div className="global-search"><Search size={17}/><input aria-label="搜索论文" placeholder="搜索标题、作者、DOI…" onKeyDown={e => { if (e.key === 'Enter') nav(`/app/papers?q=${encodeURIComponent(e.currentTarget.value)}`) }}/><kbd>⌘ K</kbd></div><div className="top-actions"><span className="avatar">A</span></div></header><main>{children}</main></div></div>
}

function Setup() { const nav = useNavigate(); const [email,setEmail]=useState(''); const [name,setName]=useState(''); const [password,setPassword]=useState(''); const [code,setCode]=useState(''); const [setupSecret,setSetupSecret]=useState(''); const [sent,setSent]=useState(false); const [error,setError]=useState('');
  return <div className="auth-page"><div className="auth-panel"><div className="brand large"><span className="brand-mark">PA</span><span>Paper Atlas</span></div><p className="eyebrow">首次部署</p><h1>创建管理员</h1><p className="muted">初始化只执行一次。请输入部署时设置的初始化令牌。</p>{error && <div className="alert error">{error}</div>}<label>初始化令牌<input type="password" value={setupSecret} onChange={e=>setSetupSecret(e.target.value)} placeholder="SETUP_SECRET" autoComplete="one-time-code"/></label><label>管理员邮箱<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" autoComplete="email"/></label><label>显示名称<input value={name} onChange={e=>setName(e.target.value)} placeholder="例如：林研究员"/></label><label>设置密码<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="至少 12 位" autoComplete="new-password"/></label><div className="code-row"><label>邮箱验证码<input inputMode="numeric" value={code} onChange={e=>setCode(e.target.value)} placeholder="6 位验证码"/></label><button className="button secondary" onClick={async()=>{try{await api('/auth/send-code',{method:'POST',body:JSON.stringify({email,purpose:'setup'})});setSent(true)}catch(e){setError((e as Error).message)}}}>{sent?'已发送':'发送验证码'}</button></div><button className="button primary full" onClick={async()=>{try{await api('/setup/admin',{method:'POST',body:JSON.stringify({email,displayName:name,password,code,setupNonce:setupSecret})});nav('/auth/login')}catch(e){setError((e as Error).message)}}}>完成初始化</button><p className="fineprint">请在服务器环境变量中配置 SMTP 后再发送验证码。</p></div></div>
}

function Login() { const nav=useNavigate(); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [code,setCode]=useState(''); const [needsCode,setNeedsCode]=useState(false); const [error,setError]=useState(''); return <div className="auth-page"><div className="auth-panel"><div className="brand large"><span className="brand-mark">PA</span><span>Paper Atlas</span></div><p className="eyebrow">管理员入口</p><h1>欢迎回来</h1><p className="muted">你的论文、笔记和研究脉络都在这里。</p>{error&&<div className="alert error">{error}</div>}<label>邮箱<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label>密码<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label>{needsCode&&<label>邮箱验证码<input inputMode="numeric" value={code} onChange={e=>setCode(e.target.value)} placeholder="输入 6 位验证码"/></label>}<button className="button primary full" onClick={async()=>{try{const result=await api<any>('/auth/login',{method:'POST',body:JSON.stringify({email,password,code})});const verificationRequired=Boolean(result?.verificationRequired||result?.data?.verificationRequired||result?.data?.status==='verification_required');if(verificationRequired&&!code){setNeedsCode(true);setError('请输入邮箱验证码完成登录');await api('/auth/send-code',{method:'POST',body:JSON.stringify({email,purpose:'login'})}).catch(()=>{});return}nav('/app/dashboard')}catch(e){const msg=(e as Error).message; if(msg.includes('验证')||msg.includes('verification')||msg.includes('verification_required')) {setNeedsCode(true);setError('请输入邮箱验证码完成登录'); await api('/auth/send-code',{method:'POST',body:JSON.stringify({email,purpose:'login'})}).catch(()=>{})} else setError(msg)}}}>登录</button><div className="auth-links"><Link to="/setup">首次部署？创建管理员</Link><span>登录受到速率限制保护</span></div></div></div> }

function Dashboard() { const [data,setData]=useState<any>(null); useEffect(()=>{dashboard().then(r=>{const raw=r.data; const stats=raw.stats||raw; setData({...stats,recent:raw.recent||[]})}).catch(()=>setData({totalPapers:0,importedLast30Days:0,unread:0,storageBytes:0,recent:[]}))},[]); const stats=[['论文总数',data?.totalPapers??'—','篇'],['近 30 天导入',data?.importedLast30Days??'—','篇'],['待阅读',data?.unread??'—','篇'],['存储占用',data?`${((data.storageBytes||0)/1073741824).toFixed(1)}`:'—','GB']]; return <Shell><div className="page-head"><div><p className="eyebrow">研究工作台</p><h1>概览</h1><p className="muted">快速了解知识库的积累与下一步阅读。</p></div><Link className="button primary" to="/app/import"><Upload size={17}/>导入论文</Link></div><section className="stat-grid">{stats.map(([label,value,unit])=><div className="stat-card" key={label}><span>{label}</span><strong>{value}</strong><small>{unit}</small></div>)}</section><section className="content-grid"><div className="panel"><div className="panel-head"><h2>最近打开</h2><Link to="/app/papers">查看全部</Link></div>{(data?.recent??[]).length===0?<Empty title="还没有论文" description="导入第一篇论文，建立你的研究地图。" action={<Link className="button secondary" to="/app/import"><Upload size={16}/>开始导入</Link>}/>:data.recent.map((p:Paper)=><PaperRow key={p.id} paper={p}/>)}</div><div className="panel"><div className="panel-head"><h2>快捷入口</h2></div><div className="quick-grid"><Link to="/app/papers"><BookOpen size={19}/><span>浏览论文库</span><small>按标签、年份筛选</small></Link><Link to="/app/taxonomy"><Tags size={19}/><span>整理分类</span><small>管理研究主题</small></Link><Link to="/app/settings/security"><Settings2 size={19}/><span>安全设置</span><small>会话与验证策略</small></Link></div></div></section></Shell> }

function PaperRow({paper}:{paper:Paper}) { return <Link className="paper-row" to={`/app/papers/${paper.id}`}><div className="paper-icon"><BookOpen size={18}/></div><div className="paper-main"><strong>{paper.title}</strong><span>{paper.authors?.map(a=>a.name).join(', ') || '作者信息待解析'} · {paper.year || '年份未知'}</span></div><span className="row-status">{paper.readingStatus==='read'?'已读':paper.readingStatus==='reading'?'阅读中':'未读'}</span></Link> }
function Empty({title,description,action}:{title:string;description:string;action?:ReactNode}) { return <div className="empty"><div className="empty-icon"><BookOpen size={24}/></div><h3>{title}</h3><p>{description}</p>{action}</div> }

function Papers() { const [items,setItems]=useState<Paper[]>([]); const [q,setQ]=useState(new URLSearchParams(location.search).get('q')||''); const [loading,setLoading]=useState(true); useEffect(()=>{setLoading(true); papers(`?q=${encodeURIComponent(q)}&pageSize=20`).then(r=>setItems(r.data.items)).catch(()=>setItems([])).finally(()=>setLoading(false))},[q]); return <Shell><div className="page-head"><div><p className="eyebrow">资料库</p><h1>论文库</h1><p className="muted">用关键词、标签或 DSL 快速定位你的研究材料。</p></div><Link className="button primary" to="/app/import"><Upload size={17}/>导入论文</Link></div><div className="toolbar"><div className="search-field"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索标题、作者、DOI、期刊…"/></div><select aria-label="排序"><option>相关性</option><option>最近添加</option><option>发表年份</option><option>标题</option></select></div><div className="papers-layout"><aside className="filters"><h3>筛选</h3><label>阅读状态<select><option>全部状态</option><option>未读</option><option>阅读中</option><option>已读</option></select></label><label>年份<input type="text" placeholder="2020-2025"/></label><div className="filter-note">支持 `title:`、`author:`、`tag:`、`year:` 等搜索语法。</div></aside><div className="panel paper-list">{loading?<div className="loading">正在查询论文…</div>:items.length===0?<Empty title="没有匹配的论文" description="调整关键词或导入新的研究材料。"/>:items.map(p=><PaperRow key={p.id} paper={p}/>)}</div></div></Shell> }
function Import() { const [files,setFiles]=useState<File[]>([]); const [message,setMessage]=useState(''); return <Shell><div className="page-head"><div><p className="eyebrow">安全导入</p><h1>导入论文</h1><p className="muted">支持 PDF、DOCX、DOC、ODT、LaTeX、TXT 和 BibTeX/RIS/CSL-JSON。</p></div></div><div className="import-panel"><label className="dropzone"><Upload size={28}/><strong>拖拽文件到这里，或点击选择</strong><span>单文件最大 200 MB，服务端会进行扩展名、MIME 和魔数校验。</span><input type="file" multiple accept=".pdf,.doc,.docx,.odt,.tex,.txt,.bib,.ris,.json" onChange={e=>setFiles(Array.from(e.target.files||[]))}/></label>{files.length>0&&<div className="file-list">{files.map(f=><div className="file-item" key={f.name}><BookOpen size={17}/><span>{f.name}</span><small>{(f.size/1048576).toFixed(1)} MB</small></div>)}</div>}<div className="import-actions"><button className="button primary" disabled={!files.length} onClick={async()=>{const fd=new FormData();files.forEach(f=>fd.append('files[]',f));try{await api('/papers/upload',{method:'POST',body:fd});setMessage('文件已进入安全扫描队列。')}catch(e){setMessage((e as Error).message)}}}><Upload size={17}/>开始扫描与解析</button>{message&&<span className="success-text">{message}</span>}</div></div></Shell> }
function Taxonomy(){return <Shell><div className="page-head"><div><p className="eyebrow">知识组织</p><h1>标签与分类</h1><p className="muted">标准分类与自定义标签并列管理，保持研究脉络清晰。</p></div></div><div className="taxonomy-grid"><div className="panel"><div className="panel-head"><h2>分类树</h2><button className="button secondary">+ 新建分类</button></div><div className="tree"><div className="tree-item root">计算机科学 <small>ACM CCS</small></div><div className="tree-item">　机器学习 <small>28 篇</small></div><div className="tree-item">　信息检索 <small>14 篇</small></div><div className="tree-item">　自然语言处理 <small>9 篇</small></div><div className="tree-item root">自定义研究 <small>Custom</small></div></div></div><div className="panel"><div className="panel-head"><h2>常用标签</h2><button className="button secondary">+ 新建标签</button></div><div className="tag-cloud"><span className="tag teal">survey</span><span className="tag blue">核心论文</span><span className="tag amber">待复现</span><span className="tag rose">方法论</span><span className="tag slate">开放获取</span></div></div></div></Shell>}

export default function App(){ const [ready,setReady]=useState<boolean|null>(null); const [authed,setAuthed]=useState(false); useEffect(()=>{setupStatus().then(r=>setReady(r.data.initialized)).catch(()=>setReady(true)); me().then(()=>setAuthed(true)).catch(()=>setAuthed(false))},[]); if(ready===null)return <div className="splash">正在连接知识库…</div>; return <Routes><Route path="/setup" element={ready?<Navigate to="/auth/login" replace/>:<Setup/>}/><Route path="/auth/login" element={authed?<Navigate to="/app/dashboard" replace/>:<Login/>}/><Route path="/app/dashboard" element={authed?<Dashboard/>:<Navigate to="/auth/login" replace/>}/><Route path="/app/papers" element={authed?<Papers/>:<Navigate to="/auth/login" replace/>}/><Route path="/app/import" element={authed?<Import/>:<Navigate to="/auth/login" replace/>}/><Route path="/app/taxonomy" element={authed?<Taxonomy/>:<Navigate to="/auth/login" replace/>}/><Route path="*" element={<Navigate to={ready?'/auth/login':'/setup'} replace/>}/></Routes> }
